# Generated by Django 2.1.4 on 2018-12-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=4000),
        ),
    ]
